-- MySQL Script generated by MySQL Workbench
-- 02/18/15 10:00:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IT111_exercise1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IT111_exercise1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IT111_exercise1` ;

-- -----------------------------------------------------
-- Table `IT111_exercise1`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT111_exercise1`.`Region` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `Region_code` VARCHAR(32) NULL,
  `Region_description` VARCHAR(32) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT111_exercise1`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT111_exercise1`.`Province` (
  `idProvince` INT NOT NULL AUTO_INCREMENT,
  `Province_code` VARCHAR(32) NULL,
  `Province_Description` VARCHAR(32) NULL,
  `Region_idRegion` INT NOT NULL,
  PRIMARY KEY (`idProvince`, `Region_idRegion`),
  INDEX `fk_Province_Region_idx` (`Region_idRegion` ASC),
  CONSTRAINT `fk_Province_Region`
    FOREIGN KEY (`Region_idRegion`)
    REFERENCES `IT111_exercise1`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT111_exercise1`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT111_exercise1`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `City_code` VARCHAR(32) NULL,
  `City_description` VARCHAR(32) NULL,
  `Province_idProvince` INT NOT NULL,
  `Province_Region_idRegion` INT NOT NULL,
  PRIMARY KEY (`idCity`, `Province_idProvince`, `Province_Region_idRegion`),
  INDEX `fk_City_Province1_idx` (`Province_idProvince` ASC, `Province_Region_idRegion` ASC),
  CONSTRAINT `fk_City_Province1`
    FOREIGN KEY (`Province_idProvince` , `Province_Region_idRegion`)
    REFERENCES `IT111_exercise1`.`Province` (`idProvince` , `Region_idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
