-- MySQL Script generated by MySQL Workbench
-- 03/26/15 08:48:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ls_dss
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ls_dss
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ls_dss` DEFAULT CHARACTER SET latin1 ;
USE `ls_dss` ;

-- -----------------------------------------------------
-- Table `ls_dss`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`auth_rule` (
  `name` VARCHAR(64) NOT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`auth_item` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  `updated_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC),
  INDEX `type` (`type` ASC),
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `ls_dss`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `firstname` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `lastname` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `roles` VARCHAR(64) CHARACTER SET 'latin1' NOT NULL,
  `company` INT(11) NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles` (`roles` ASC),
  INDEX `company` (`company` ASC),
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`roles`)
    REFERENCES `ls_dss`.`auth_item` (`name`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `ls_dss`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`auth_assignment` (
  `item_name` VARCHAR(64) NOT NULL,
  `user_id` INT(64) NOT NULL,
  `created_at` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  UNIQUE INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `ls_dss`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_assignment_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `ls_dss`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`auth_item_child` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `ls_dss`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `ls_dss`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`client` (
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `contact_number` INT(11) NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `company_position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`firstname`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`inventory` (
  `Code` INT(11) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Color` VARCHAR(45) NOT NULL,
  `Specs` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `PurchasedDate` DATE NOT NULL,
  `Quantity` VARCHAR(45) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`Code`, `user_id`),
  INDEX `fk_inventory_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_inventory_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ls_dss`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ls_dss`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ls_dss`.`uploaded_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ls_dss`.`uploaded_file` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `filename` VARCHAR(256) NOT NULL,
  `size` INT(11) NOT NULL,
  `type` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
