-- MySQL Script generated by MySQL Workbench
-- 02/18/15 10:59:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema it111_exercise1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema it111_exercise1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `it111_exercise1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `it111_exercise1` ;

-- -----------------------------------------------------
-- Table `it111_exercise1`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise1`.`Region` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(32) NULL,
  `region_description` VARCHAR(32) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it111_exercise1`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise1`.`Region` (
  `idRegion` INT NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(32) NULL,
  `region_description` VARCHAR(32) NULL,
  PRIMARY KEY (`idRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it111_exercise1`.`Province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise1`.`Province` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `province_code` VARCHAR(32) NULL,
  `province_description` VARCHAR(32) NULL,
  `region_idRegion` INT NOT NULL,
  PRIMARY KEY (`id`, `region_idRegion`),
  INDEX `fk_Province_Region_idx` (`region_idRegion` ASC),
  CONSTRAINT `fk_Province_Region`
    FOREIGN KEY (`region_idRegion`)
    REFERENCES `it111_exercise1`.`Region` (`idRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `it111_exercise1`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise1`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `city_code` VARCHAR(32) NULL,
  `city_description` VARCHAR(32) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`idCity`, `province_id`),
  INDEX `fk_City_Province1_idx` (`province_id` ASC),
  CONSTRAINT `fk_City_Province1`
    FOREIGN KEY (`province_id`)
    REFERENCES `it111_exercise1`.`Province` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
